"""add dealer_id to quotes and policies

Revision ID: 07a277e35158
Revises: 7b89730b6d6c
Create Date: 2026-04-16 15:00:22.622054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a277e35158'
down_revision: Union[str, Sequence[str], None] = '7b89730b6d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('dealer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'policies', 'dealers', ['dealer_id'], ['id'])
    op.add_column('quotes', sa.Column('dealer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quotes', 'dealers', ['dealer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'dealer_id')
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'dealer_id')
    # ### end Alembic commands ###
