"""add vehicle_category to quotes

Revision ID: 29909565d01c
Revises: c8935fa57e3a
Create Date: 2026-04-09 17:18:52.700544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29909565d01c'
down_revision: Union[str, Sequence[str], None] = 'c8935fa57e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('vehicle_category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'vehicle_category')
    # ### end Alembic commands ###
