"""add allowed_products and favicon_url to tenant

Revision ID: 652fdad2fc58
Revises: 0d9fd526923d
Create Date: 2026-04-16 14:14:56.894918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652fdad2fc58'
down_revision: Union[str, Sequence[str], None] = '0d9fd526923d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('allowed_products', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('favicon_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'favicon_url')
    op.drop_column('tenants', 'allowed_products')
    # ### end Alembic commands ###
