"""fix_rate_column_precision

Revision ID: 8428eed903f1
Revises: 8f022dcb5e06
Create Date: 2026-04-19 15:52:49.008660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8428eed903f1'
down_revision: Union[str, Sequence[str], None] = '8f022dcb5e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policies', 'dealer_fee_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=True)
    op.alter_column('policies', 'broker_commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=True)
    op.alter_column('policy_transactions', 'dealer_fee_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=True)
    op.alter_column('policy_transactions', 'broker_commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policy_transactions', 'broker_commission_rate',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('policy_transactions', 'dealer_fee_rate',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('policies', 'broker_commission_rate',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('policies', 'dealer_fee_rate',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
