"""redesign_policy_and_transactions

Revision ID: 8f022dcb5e06
Revises: 
Create Date: 2026-04-19 15:51:15.367280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f022dcb5e06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('term_months', sa.Integer(), nullable=False))
    op.add_column('policies', sa.Column('payment_type', sa.Enum('CASH', 'FINANCE', name='paymenttype'), nullable=False))
    op.add_column('policies', sa.Column('dealer_fee_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('policies', sa.Column('broker_commission_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('policies', sa.Column('policy_data', sa.JSON(), nullable=False))
    op.drop_column('policies', 'current_data')
    op.add_column('policy_transactions', sa.Column('dealer_fee_delta', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('policy_transactions', sa.Column('broker_commission_delta', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('policy_transactions', sa.Column('dealer_fee_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('policy_transactions', sa.Column('broker_commission_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('policy_transactions', sa.Column('snapshot', sa.JSON(), nullable=True))
    op.drop_column('policy_transactions', 'commission_data')
    op.drop_column('policy_transactions', 'data_before')
    op.drop_column('policy_transactions', 'data_after')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_transactions', sa.Column('data_after', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('policy_transactions', sa.Column('data_before', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('policy_transactions', sa.Column('commission_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('policy_transactions', 'snapshot')
    op.drop_column('policy_transactions', 'broker_commission_rate')
    op.drop_column('policy_transactions', 'dealer_fee_rate')
    op.drop_column('policy_transactions', 'broker_commission_delta')
    op.drop_column('policy_transactions', 'dealer_fee_delta')
    op.add_column('policies', sa.Column('current_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('policies', 'policy_data')
    op.drop_column('policies', 'broker_commission_rate')
    op.drop_column('policies', 'dealer_fee_rate')
    op.drop_column('policies', 'payment_type')
    op.drop_column('policies', 'term_months')
    # ### end Alembic commands ###
