"""add finance_company to tenant

Revision ID: b836143ffc39
Revises: a22bd56124a4
Create Date: 2026-04-09 15:19:00.769479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b836143ffc39'
down_revision: Union[str, Sequence[str], None] = 'a22bd56124a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('finance_company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'finance_company')
    # ### end Alembic commands ###
