"""add broker_commission_rate to tenant

Revision ID: cfdd8d0201ae
Revises: 07a277e35158
Create Date: 2026-04-16 15:31:28.799622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdd8d0201ae'
down_revision: Union[str, Sequence[str], None] = '07a277e35158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('broker_commission_rate', sa.Numeric(precision=5, scale=2), server_default='15.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'broker_commission_rate')
    # ### end Alembic commands ###
