"""add policy transaction log

Revision ID: d3e73b81c75b
Revises: 7d89a3f74f25
Create Date: 2026-04-15 11:35:25.193233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e73b81c75b'
down_revision: Union[str, Sequence[str], None] = '7d89a3f74f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('BIND', 'ISSUE', 'ENDORSEMENT', 'CANCELLATION', 'REINSTATEMENT', name='transactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.Column('premium_delta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_transactions_id'), 'policy_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_transactions_id'), table_name='policy_transactions')
    op.drop_table('policy_transactions')
    # ### end Alembic commands ###
