"""add commission_data to policy_transactions and dealer_fee broker_commission to policies

Revision ID: f3c1a8b7a256
Revises: cfdd8d0201ae
Create Date: 2026-04-16 16:01:48.775269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c1a8b7a256'
down_revision: Union[str, Sequence[str], None] = 'cfdd8d0201ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('dealer_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('policies', sa.Column('broker_commission', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('policy_transactions', sa.Column('commission_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_transactions', 'commission_data')
    op.drop_column('policies', 'broker_commission')
    op.drop_column('policies', 'dealer_fee')
    # ### end Alembic commands ###
