"""add term_months to quotes

Revision ID: f9111780d6f3
Revises: b836143ffc39
Create Date: 2026-04-09 16:04:51.488061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9111780d6f3'
down_revision: Union[str, Sequence[str], None] = 'b836143ffc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('term_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'term_months')
    # ### end Alembic commands ###
